services:
  backend:
    image: backend:v1
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1234:8000" # host:container
    env_file:
      - ./backend/.env
    networks:
      - agent-network
    # volumes: # mount
    #   - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: frontend:v1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1235:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - agent-network

networks:
  agent-network:
    name: agent-network